### ISSUE TITLE
Radar sometimes crashes if it refreshes when the drop-down list of pipelines is open

### ISSUE THREAD

**Issue by davewalter** [ryanmoran/Radar#2]
This has happened twice to me this evening. Perhaps it would be good to pend the refresh if the user has the drop-down list of pipelines open? I've also noticed that if Radar does successfully refresh in this state, then I sometimes cannot click on a pipeline/group/job to open it, and I have to close the drop-down and re-navigate to the desired location.

Let me know if you want more details.

Thanks,
Dave

**Comment by ryanmoran** [comment]
I've updated the UI rendering to wait until the menu is closed to update the UI. Don't think this is the right long-term solution, but it should prevent it from crashing or rendering the menu items "unclickable". This is out in the latest version (0.15). Let me know if you still see issues.
